const data = {
    "first_name": "Fidan",
    "last_name": "Ismayilova",
    "job_title": "Web-Developer",
    "photo": "./images/avatar.jpg",
    "phone": "+994xxxxxxxxx",
    "phone_icon": "./images/phone-alt-solid.svg",
    "email": "admin@fidan.com.az",
    "email_icon": "./images/envelope-square-solid.svg",
    "skype": "skype.example",
    "skype_name": "Skype",
    "skype_icon": "./images/skype-brands.svg",
    "linkedin": "https://www.linkedin.com/in/fidan-ismailova-13637a20b/",
    "linkedin_name": "LinkedIn",
    "linkedin_icon": "./images/linkedin-brands.svg",
    "address": "Azerbaijan, Baku",
    "skills": [
        "Creative Development",
        "Branding & Identity",
        "Project Management",
        "Contact Negotiation",
        "Ad Buying & Planning",
        "Product Positioning",
        "Visual Merchandising",
        "Search Engine Ads",
        "Process Improvement",
        "Market Strategizing",
        "Adobe Creative Suite",
        "Microsoft Office 2016",
        "Google Web Analytics",
        "Fluent in Spanish",
    ],
    "education": [
        ["National Aviation Academy (engineer)", "2004-2009"],
    ],
    "achievements": [
        "qwerty","qwerty","qwerty"
    ],
    "profile": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quidem quasi dolor rem, accusamus similique cupiditate, architecto eveniet soluta totam provident officiis! Quis totam reiciendis ducimus quas, quam vel eos cumque."
};